name: voice_clock
description: Voice clock.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2

  speech_to_text: ^0.7.2
  flutter_tts: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: PressStart2P
      fonts:
        - asset: third_party/PressStart2P-Regular.ttf
